### ISSUE TITLE
[Excption in infer ]GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by mengdalida** [voicepaw/so-vits-svc-fork#404] opened 2023-04-19 14:23 UTC
**Describe the bug**
raceback (most recent call last):
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/so_vits_svc_fork/__main__.py", line 248, in infer
    infer(
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/so_vits_svc_fork/inference/main.py", line 56, in infer
    audio = svc_model.infer_silence(
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/so_vits_svc_fork/inference/core.py", line 284, in infer_silence
    audio_chunk_pad_infer_tensor, _ = self.infer(
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/so_vits_svc_fork/inference/core.py", line 218, in infer
    audio = self.net_g.infer(
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/so_vits_svc_fork/modules/synthesizers.py", line 232, in infer
    o = self.dec(z * c_mask, g=g, f0=f0)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/so_vits_svc_fork/modules/decoders/hifigan/_models.py", line 287, in forward
    x = self.ups[i](x)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/so-vits-svc-fork/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 801, in forward
    return F.conv_transpose1d(
RuntimeError: GET was unable to find an engine to execute this computation

**To Reproduce**
svc infer output/dayang_0.300_9.900.wav -c config.json -m G_sora_100.pth

dangyang file is about 8 secound add config.json and G_sora_100.pth, I got it from https://huggingface.co/TachibanaKimika/so-vits-svc-4.0-models no any modify

**Additional context**

**Comment by 34j** [comment] 2023-05-04 10:43
Duplicate of #339

**Closed** 2023-05-04 10:43 UTC
Labels: bug
