### ISSUE TITLE
Training does not start

### ISSUE THREAD

**Issue by ALEXuH** [voicepaw/so-vits-svc-fork#465] opened 2023-04-23 01:29 UTC
**Describe the bug**
run svc train then log has been static 
A small part of gpu resource 1.3g is used, I don’t know if this is normal, my environment: ubuntu22.04 and two 4090

![1682213196772](https://user-images.githubusercontent.com/32250185/233814414-2554ca43-3ca8-4437-8859-30c55120bff1.png)
![1682213297517](https://user-images.githubusercontent.com/32250185/233814421-7bf4f2ee-d593-4283-b372-6a296f6449c6.png)

**Comment by 34j** [comment] 2023-04-23 03:41
Duplicate of #405

**Closed** 2023-04-23 03:41 UTC
Labels: bug
