### ISSUE TITLE
The infer button disappeared from the GUI

### ISSUE THREAD

**Issue by Diegoestropini** [voicepaw/so-vits-svc-fork#608] opened 2023-05-10 19:25 UTC
I have a problem with the infer button that is not showing up. I had version 3.11 and it was working perfectly, but when I updated to 3.14.1, the button disappeared. Is there any way to fix it?

**Comment by 34j** [comment] 2023-05-11 01:46
Duplicate of #505

**Closed** 2023-05-11 01:46 UTC
Labels: bug
