### ISSUE TITLE
GUI resets to default settings.

### ISSUE THREAD

**Issue by ariikamusic** [voicepaw/so-vits-svc-fork#733] opened 2023-06-05 21:31 UTC
### Describe the bug

After first starting up the GUI, I am adding all my files and setting up the F0 settings, etc. After I click on the Infer button, the GUI resets itself to the default settings, and also renders it in the default settings.

(Picture 1 is the settings I made myself, Picture 2 is the GUI resetting itself to default settings after clicking Infer.)

Note: This only happens after first starting up the GUI. 

![image](https://github.com/voicepaw/so-vits-svc-fork/assets/135545749/070ff185-8798-42f6-aacc-545c67d16dd6)

![image](https://github.com/voicepaw/so-vits-svc-fork/assets/135545749/9080a852-4377-4013-a701-66a3e67c95bc)

### To Reproduce

Start up the GUI, put in settings, and press Infer.

### Additional context

Unfortunately I've always had experienced issue, even on a different Desktop PC, and after upgrading to Windows 11.

### Version

4.0.1

### Platform

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by tomakorea** [comment] 2023-06-07 09:52
Same problem here, it's been few releases that it does this. The workaround for me is just to use INFER on a very tiny wav file in order to make the first pass very quick. Then I can use it properly. The bug is the same on my Windows 10 pc and on my Mac.

**Comment by 34j** [comment] 2023-06-07 11:59
Duplicate of

**Closed** 2023-06-07 11:59 UTC
Labels: bug
