### ISSUE TITLE
there is an error with the client socket connection

### ISSUE THREAD

**Issue by svigx** [voicepaw/so-vits-svc-fork#501] opened 2023-04-27 14:23 UTC
I get this errors when i do svc train -t, i tried with a different env in conda but same error.

[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-F0HD9ID]:50067 (system error: 10049 - The requested address is not valid in its context.).

C:\Users\Ivs\.conda\envs\svc\python.exe: Error while finding module specification for '__main__' (ValueError: __main__.__spec__ is None)

**Comment by 34j** [comment] 2023-04-28 08:16
Duplicate of #481

**Closed by 34j** 2023-04-28 08:16 UTC
Labels: bug
